"""add_grades_table_and_position_grade_id

Revision ID: 6a18031ca663
Revises: c05a68f394a1
Create Date: 2026-09-08 13:54:22.683413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a18031ca663'
down_revision: Union[str, None] = 'c05a68f394a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Default grades seeded for every EXISTING company (see CLAUDE.md § Authentication &
# Authorization) — (code, name, level, can_manage_employees, can_manage_products,
# can_manage_positions, can_view_salary). A company created AFTER this migration runs does
# NOT get these automatically; only this one-time backfill for pre-existing companies is in
# scope here — new companies start with zero grades until someone creates some via the new
# Grades page.
_GRADE_SEED_DATA: list[tuple[str, str, int, bool, bool, bool, bool]] = [
    ("S", "Staff", 1, False, True, False, False),
    ("M", "Manager", 2, True, True, False, False),
    ("HR", "HR", 2, True, False, False, True),
    ("C", "Chief", 3, True, True, True, True),
    ("A", "Admin", 4, True, True, True, True),
]


def _leading_letter_prefix(grade_code: str) -> str:
    """"M1" -> "M", "S2" -> "S", "10M" -> "" (no leading letters at all) — a contiguous run
    of alphabetic characters starting at position 0, uppercased. Anything that doesn't
    resolve to one of this migration's seeded codes for its own company is left with
    grade_id=NULL and reported in the upgrade log rather than silently dropped."""
    prefix = ""
    for ch in grade_code.strip():
        if ch.isalpha():
            prefix += ch
        else:
            break
    return prefix.upper()


def upgrade() -> None:
    # ### schema changes (autogenerated, hand-adjusted — grade_code is deliberately NOT
    # dropped by this migration; see the module the Position model comment for why) ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('can_manage_employees', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_manage_products', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_manage_positions', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_view_salary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_grades_company_id_code')
    )
    op.create_index('ix_grades_company_id', 'grades', ['company_id'], unique=False)
    op.add_column('positions', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.add_column('positions', sa.Column('can_view_salary', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('ix_positions_grade_id', 'positions', ['grade_id'], unique=False)
    op.create_foreign_key('fk_positions_grade_id_grades', 'positions', 'grades', ['grade_id'], ['id'])
    # NOTE: 'positions.grade_code' is intentionally left in place — see the docstring on
    # Position in app/models/position.py and this migration's module docstring above. Drop
    # it in a separate follow-up migration once the backfill below has been verified.
    # ### end schema changes ###

    # --- data migration: seed the 5 default grades for every existing company, then
    # backfill positions.grade_id from the OLD grade_code column's leading letter prefix ---
    connection = op.get_bind()

    companies_table = sa.table("companies", sa.column("id", sa.Integer()))
    grades_table = sa.table(
        "grades",
        sa.column("id", sa.Integer()),
        sa.column("company_id", sa.Integer()),
        sa.column("code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("level", sa.Integer()),
        sa.column("can_manage_employees", sa.Boolean()),
        sa.column("can_manage_products", sa.Boolean()),
        sa.column("can_manage_positions", sa.Boolean()),
        sa.column("can_view_salary", sa.Boolean()),
    )
    positions_table = sa.table(
        "positions",
        sa.column("id", sa.Integer()),
        sa.column("company_id", sa.Integer()),
        sa.column("grade_code", sa.String()),
        sa.column("grade_id", sa.Integer()),
    )

    company_ids = [row.id for row in connection.execute(sa.select(companies_table.c.id))]

    # company_id -> {code -> grade_id}, filled in as each company's 5 seed grades are inserted
    grade_id_by_company_and_code: dict[int, dict[str, int]] = {}

    for company_id in company_ids:
        grade_id_by_company_and_code[company_id] = {}
        for code, name, level, mgmt_employees, mgmt_products, mgmt_positions, view_salary in _GRADE_SEED_DATA:
            result = connection.execute(
                grades_table.insert()
                .values(
                    company_id=company_id,
                    code=code,
                    name=name,
                    level=level,
                    can_manage_employees=mgmt_employees,
                    can_manage_products=mgmt_products,
                    can_manage_positions=mgmt_positions,
                    can_view_salary=view_salary,
                )
                .returning(grades_table.c.id)
            )
            grade_id_by_company_and_code[company_id][code] = result.scalar_one()

    existing_positions = connection.execute(
        sa.select(positions_table.c.id, positions_table.c.company_id, positions_table.c.grade_code).where(
            positions_table.c.grade_code.isnot(None)
        )
    ).all()

    unmatched: list[tuple[int, str]] = []
    for position_id, company_id, grade_code in existing_positions:
        prefix = _leading_letter_prefix(grade_code)
        matched_grade_id = grade_id_by_company_and_code.get(company_id, {}).get(prefix)
        if matched_grade_id is None:
            unmatched.append((position_id, grade_code))
            continue
        connection.execute(
            positions_table.update()
            .where(positions_table.c.id == position_id)
            .values(grade_id=matched_grade_id)
        )

    if unmatched:
        print(  # noqa: T201 -- deliberate migration-time diagnostic, not application logging
            "WARNING: add_grades_table_and_position_grade_id could not match grade_code to "
            f"a known grade prefix for {len(unmatched)} position(s) — left with grade_id=NULL "
            f"(position_id, grade_code): {unmatched}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_positions_grade_id_grades', 'positions', type_='foreignkey')
    op.drop_index('ix_positions_grade_id', table_name='positions')
    op.drop_column('positions', 'can_view_salary')
    op.drop_column('positions', 'grade_id')
    op.drop_index('ix_grades_company_id', table_name='grades')
    op.drop_table('grades')
    # ### end Alembic commands ###
