"""remove_position_permission_columns_add_special_permissions

Revision ID: 7a25723b0a8f
Revises: 6a18031ca663
Create Date: 2026-09-08 15:06:00.614104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a25723b0a8f'
down_revision: Union[str, None] = '6a18031ca663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### schema: new table (autogenerated) ###
    op.create_table('employee_special_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('can_manage_employees', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_manage_products', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_manage_positions', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_view_salary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    # ### end schema: new table ###

    # --- data preservation: positions.can_manage_employees/products/positions/can_view_salary
    # are about to be dropped. Permission now comes purely from the Position's Grade (live,
    # re-evaluated every request) instead of a one-time copy stored on the Position itself.
    # For any position whose stored flags grant something its Grade does NOT already grant
    # (including any position with no grade at all, where the grade contributes nothing), that
    # extra access would silently disappear for every employee in that position once these
    # columns are gone — unless preserved. So: for each such "surplus" flag, seed an
    # employee_special_permissions row (one per affected EMPLOYEE, since that table is
    # per-employee, not per-position) carrying exactly the surplus, and nothing else. An
    # employee whose position's flags were already fully covered by its Grade gets no row at
    # all — there is nothing to preserve for them.
    connection = op.get_bind()

    positions_table = sa.table(
        "positions",
        sa.column("id", sa.Integer()),
        sa.column("grade_id", sa.Integer()),
        sa.column("can_manage_employees", sa.Boolean()),
        sa.column("can_manage_products", sa.Boolean()),
        sa.column("can_manage_positions", sa.Boolean()),
        sa.column("can_view_salary", sa.Boolean()),
    )
    grades_table = sa.table(
        "grades",
        sa.column("id", sa.Integer()),
        sa.column("can_manage_employees", sa.Boolean()),
        sa.column("can_manage_products", sa.Boolean()),
        sa.column("can_manage_positions", sa.Boolean()),
        sa.column("can_view_salary", sa.Boolean()),
    )
    employees_table = sa.table(
        "employees",
        sa.column("id", sa.Integer()),
        sa.column("position_id", sa.Integer()),
    )
    special_permissions_table = sa.table(
        "employee_special_permissions",
        sa.column("employee_id", sa.Integer()),
        sa.column("can_manage_employees", sa.Boolean()),
        sa.column("can_manage_products", sa.Boolean()),
        sa.column("can_manage_positions", sa.Boolean()),
        sa.column("can_view_salary", sa.Boolean()),
    )

    grade_flags_by_id: dict[int, tuple[bool, bool, bool, bool]] = {
        row.id: (
            row.can_manage_employees,
            row.can_manage_products,
            row.can_manage_positions,
            row.can_view_salary,
        )
        for row in connection.execute(
            sa.select(
                grades_table.c.id,
                grades_table.c.can_manage_employees,
                grades_table.c.can_manage_products,
                grades_table.c.can_manage_positions,
                grades_table.c.can_view_salary,
            )
        )
    }

    # position_id -> (surplus_manage_employees, surplus_manage_products, surplus_manage_positions, surplus_view_salary)
    surplus_by_position_id: dict[int, tuple[bool, bool, bool, bool]] = {}
    for position in connection.execute(
        sa.select(
            positions_table.c.id,
            positions_table.c.grade_id,
            positions_table.c.can_manage_employees,
            positions_table.c.can_manage_products,
            positions_table.c.can_manage_positions,
            positions_table.c.can_view_salary,
        )
    ):
        grade_flags = grade_flags_by_id.get(position.grade_id, (False, False, False, False))
        position_flags = (
            position.can_manage_employees,
            position.can_manage_products,
            position.can_manage_positions,
            position.can_view_salary,
        )
        surplus = tuple(
            bool(pos_flag) and not bool(grade_flag)
            for pos_flag, grade_flag in zip(position_flags, grade_flags, strict=True)
        )
        if any(surplus):
            surplus_by_position_id[position.id] = surplus

    seeded_count = 0
    if surplus_by_position_id:
        affected_employees = connection.execute(
            sa.select(employees_table.c.id, employees_table.c.position_id).where(
                employees_table.c.position_id.in_(surplus_by_position_id.keys())
            )
        ).all()

        for employee in affected_employees:
            surplus = surplus_by_position_id[employee.position_id]
            connection.execute(
                special_permissions_table.insert().values(
                    employee_id=employee.id,
                    can_manage_employees=surplus[0],
                    can_manage_products=surplus[1],
                    can_manage_positions=surplus[2],
                    can_view_salary=surplus[3],
                )
            )
            seeded_count += 1

    print(  # noqa: T201 -- deliberate migration-time diagnostic, not application logging
        "INFO: remove_position_permission_columns_add_special_permissions seeded "
        f"{seeded_count} employee_special_permissions row(s) to preserve permissions that "
        "were granted directly on a Position beyond what its Grade already grants."
    )

    # ### schema: drop the now-obsolete columns (autogenerated, hand-adjusted — grade_code
    # stays untouched, same as every migration since it was deprecated) ###
    op.drop_column('positions', 'can_manage_products')
    op.drop_column('positions', 'can_manage_employees')
    op.drop_column('positions', 'can_view_salary')
    op.drop_column('positions', 'can_manage_positions')
    # ### end schema changes ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: this restores the COLUMNS, not the data — the surplus permissions preserved above
    # were merged into employee_special_permissions (per-employee), which has no way to be
    # split back apart into per-position values. Every restored column comes back all-False.
    op.add_column('positions', sa.Column('can_manage_positions', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('positions', sa.Column('can_view_salary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('positions', sa.Column('can_manage_employees', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('positions', sa.Column('can_manage_products', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_table('employee_special_permissions')
    # ### end Alembic commands ###
