"""add_position_permission_columns

Revision ID: c05a68f394a1
Revises: b66d65b8f6d1
Create Date: 2026-09-03 14:50:35.211317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05a68f394a1'
down_revision: Union[str, None] = 'b66d65b8f6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('grade_code', sa.String(length=16), nullable=True))
    op.add_column('positions', sa.Column('can_manage_employees', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('positions', sa.Column('can_manage_products', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('positions', sa.Column('can_manage_positions', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'can_manage_positions')
    op.drop_column('positions', 'can_manage_products')
    op.drop_column('positions', 'can_manage_employees')
    op.drop_column('positions', 'grade_code')
    # ### end Alembic commands ###
